"""Shared domain constants. No I/O, no FastAPI."""

from __future__ import annotations

DISCLAIMER = (
    "POLARIS is decision-support research software, not an official warning service. "
    "Outputs must not be treated as evacuation orders or CAP/OFFICIAL alerts. "
    "A human operator must review every DRAFT alert before any operational action."
)

EVIDENCE_IMPLEMENTED = "IMPLEMENTED"
EVIDENCE_DESIGNED = "DESIGNED"
EVIDENCE_PLACEHOLDER = "PLACEHOLDER"
EVIDENCE_NOT_IMPLEMENTED = "NOT_IMPLEMENTED"

DATA_CLASS_SIMULATED = "SIMULATED"
DATA_CLASS_HISTORICAL_REPLAY = "HISTORICAL_REPLAY"
DATA_CLASS_LIVE = "LIVE"
DATA_CLASS_LIVE_INTEGRATED = "LIVE_INTEGRATED"
ALLOWED_DATA_CLASSES = frozenset(
    {DATA_CLASS_SIMULATED, DATA_CLASS_HISTORICAL_REPLAY, DATA_CLASS_LIVE_INTEGRATED}
)
ALLOWED_DATA_CLASSES_V1 = frozenset({DATA_CLASS_SIMULATED, DATA_CLASS_HISTORICAL_REPLAY})

EVIDENCE_EXPERIMENTAL = "EXPERIMENTAL"
EVIDENCE_HISTORICALLY_VALIDATED = "HISTORICALLY_VALIDATED"

PHI_MODES = frozenset({"DETECTION", "NOWCAST", "FORECAST"})
PHI_MODES_EARTHQUAKE = frozenset({"RAPID_DETECTION", "EEW"})
PHI_MODES_TSUNAMI = frozenset({"EVENT_TRIGGERED"})
PHI_MODES_DECLARED = PHI_MODES | PHI_MODES_EARTHQUAKE | PHI_MODES_TSUNAMI
QUALITY_FLAGS = frozenset({"unknown", "raw", "qc_pass", "qc_fail"})

HAZARD_FLOOD = "flood"
HAZARD_FLASH_FLOOD = "flash_flood"
HAZARD_LANDSLIDE = "landslide"
HAZARD_WILDFIRE = "wildfire"
HAZARD_DROUGHT = "drought"
HAZARD_HEAT = "heat"
HAZARD_CYCLONE = "cyclone"
HAZARD_SMOKE = "smoke"
HAZARD_EARTHQUAKE = "earthquake"
HAZARD_TSUNAMI = "tsunami"
HAZARD_VOLCANO = "volcano"
HAZARD_EROSION_SUBSIDENCE = "erosion_subsidence"

ALERT_STATUS_DRAFT = "DRAFT"
