#!/usr/bin/env python3
"""Scaffold a Digital Testbed scenario YAML under simulation/scenarios/."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from generators._common import ROOT, provenance_json, write  # noqa: E402

NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def scaffold(name: str, *, hazard_id: str, force: bool) -> list:
    if not NAME_RE.match(name):
        raise SystemExit(f"invalid scenario_id {name!r}; use kebab-case")

    created = []
    path = ROOT / "simulation" / "scenarios" / f"{name}.yaml"
    if write(
        path,
        f"""scenario_id: {name}
seed: 42
hazard_id: {hazard_id}
data_class: SIMULATED
evidence: PLACEHOLDER
formula_version: "0.0.0-not-implemented"
notes: >
  Scaffolded scenario — wire fixture paths before running PHI.
  Generated by generators/scenario/scaffold.py.
""",
        force=force,
    ):
        created.append(path)

    prov = ROOT / "simulation" / "scenarios" / f"{name}.provenance.json"
    if write(
        prov,
        provenance_json(
            generator="generators/scenario/scaffold.py",
            entity_id=name,
            evidence="PLACEHOLDER",
        ),
        force=force,
    ):
        created.append(prov)
    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a scenario YAML")
    parser.add_argument("--name", required=True)
    parser.add_argument("--hazard", default="flood", dest="hazard_id")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    created = scaffold(args.name, hazard_id=args.hazard_id, force=args.force)
    for path in created:
        print(path.relative_to(ROOT))
    if not created:
        print("already exists (pass --force to overwrite)", file=sys.stderr)


if __name__ == "__main__":
    main()
