#!/usr/bin/env python3
"""Scaffold a POLARIS hazard plugin.

Creates interface, placeholder impl, config schema, unit test, README, provenance.
Does not implement PHI.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def write(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def scaffold(name: str, force: bool) -> list[Path]:
    if not NAME_RE.match(name):
        raise SystemExit(f"invalid hazard name {name!r}; use snake_case")

    created: list[Path] = []

    def track(path: Path, content: str) -> None:
        existed = path.exists()
        write(path, content, force=force)
        if force or not existed:
            created.append(path)

    hazard_dir = ROOT / "hazards" / name
    track(
        hazard_dir / "README.md",
        f"""# hazards/{name}

**Evidence:** PLACEHOLDER

Scaffolded plugin for `{name}`. PHI is **NOT IMPLEMENTED**.

Generated by `generators/hazard/scaffold.py`.
""",
    )
    track(
        hazard_dir / "interface.py",
        f'''"""Port for hazard `{name}`. Evidence: PLACEHOLDER."""

from __future__ import annotations

from typing import Protocol


class {name.title().replace("_", "")}Model(Protocol):
    formula_version: str

    def phi(self, observation: dict) -> None:
        """Intentionally unimplemented in P0."""
        raise NotImplementedError("PHI is not implemented in P0")
''',
    )
    track(
        hazard_dir / "placeholder.py",
        f'''"""Placeholder implementation for `{name}`."""

from __future__ import annotations

FORMULA_VERSION = "0.0.0-not-implemented"
HAZARD_ID = "{name}"
EVIDENCE = "PLACEHOLDER"


def describe() -> dict[str, str]:
    return {{
        "hazard_id": HAZARD_ID,
        "formula_version": FORMULA_VERSION,
        "evidence": EVIDENCE,
    }}
''',
    )
    track(
        ROOT / "configs" / "hazards" / f"{name}.yaml",
        f"""# Hazard config stub — {name}
# Evidence: PLACEHOLDER. No PHI implementation.

hazard_id: {name}
evidence: PLACEHOLDER
formula_version: "0.0.0-not-implemented"
""",
    )
    track(
        ROOT / "schemas" / "hazard" / f"{name}.yaml",
        f"""# Config schema fragment for hazard `{name}`
# Evidence: DESIGNED contract

hazard_id: {name}
type: object
required: [hazard_id, evidence]
""",
    )
    test_path = ROOT / "tests" / "unit" / "hazards" / f"test_{name}_placeholder.py"
    track(
        test_path,
        f'''"""Placeholder tests for hazard `{name}`."""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "hazards" / "{name}"))

from placeholder import EVIDENCE, HAZARD_ID, describe  # noqa: E402


def test_placeholder_metadata() -> None:
    meta = describe()
    assert meta["hazard_id"] == HAZARD_ID == "{name}"
    assert meta["evidence"] == EVIDENCE == "PLACEHOLDER"
    assert meta["formula_version"].endswith("not-implemented")
''',
    )
    track(
        hazard_dir / "provenance.json",
        json.dumps(
            {
                "generator": "generators/hazard/scaffold.py",
                "hazard_id": name,
                "utc": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
                "evidence": "PLACEHOLDER",
                "formula_version": "0.0.0-not-implemented",
            },
            indent=2,
        )
        + "\n",
    )
    return created


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a POLARIS hazard plugin")
    parser.add_argument("--name", required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    created = scaffold(args.name, force=args.force)
    for path in created:
        print(path.relative_to(ROOT))
    if not created:
        print("already exists (pass --force to overwrite)", file=sys.stderr)


if __name__ == "__main__":
    main()
